site_name: "Intric Dokumentation"
site_description: "Användardokumentation för Intric"
site_author: "Sundsvalls kommun / Intric Team"

repo_url: https://github.com/sundsvallai/intric
repo_name: 'GitHub'
edit_uri: 'edit/main/docs/'

extra:
  platform_name: "Intric" # Korrekt indragning

theme:
  name: material # Denna SKA vara med
  custom_dir: overrides
  language: sv
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand # Bra för vänsternavigering
    - navigation.sections # Visar sektioner i vänsternavigering tydligare
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Byt till mörkt läge
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Byt till ljust läge
  font:
    text: Arial
    code: Roboto Mono
  icon:
    logo: assets/images/logo.svg
    favicon: assets/images/favicon.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences: # Konfiguration för bl.a. Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # För content tabs (kan tas bort om du inte använder)
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - awesome-pages
  - minify
  - redirects
  - mermaid2
  # - git-revision-date-localized:
  #     type: date
  #     locale: sv
  #     fallback_to_build_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: '100%'
      height: auto
      zoomable: true
      draggable: true

# nav: är bortkommenterad tack vare awesome-pages